name: foodapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # allows painting and displaying SVG files
  flutter_svg: ^0.22.0

  # It provides common validation options
  form_field_validator: ^1.1.0

  # for showing a country code selector
  country_code_picker: ^2.0.2

  # It provides easy access to platform specific location services
  geolocator: ^7.3.1

  # It provides easy geocoding and reverse-geocoding features
  geocoding: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/Illustrations/

  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/font/SF Pro Text/SFProText-Regular.ttf
        - asset: assets/font/SF Pro Text/SFProText-Bold.ttf
          weight: 700
        - asset: assets/font/SF Pro Text/SFProText-Semibold.ttf
          weight: 600
        - asset: assets/font/SF Pro Text/SFProText-Medium.ttf
          weight: 500

